### ISSUE TITLE
Running NodeJS server in Docker Container

### ISSUE THREAD

**Issue by ahmad2smile** [rikukissa/typehole#13]
typings not working when code is running inside a container. Is there any port I can expose to make it work or some config?

**Comment by ahmad2smile** [comment]
Any idea how to do it? afaik, this can't be done unless `typehole` runtime calls `host.docker.internal` instead of `localhost` and docker container is created with `network_mode: host`, even which in my case can't be done as my container connects to a docker swarm networks so I can't replace those out.

**Comment by rikukissa** [comment]
Closing the issue for now. Please feel free to reopen if you have issues connecting from your code to the extension after upgrading the extension and the runtime.

**Comment by ahmad2smile** [comment]
I really appreciate your quick response and update. This is very useful, I'm still trying to make it work with my "work" project as there is where I need this the most.

The issues I'm facing are very particular to my own specific usecase. I can not use 3rd party servers at all for work, for that reason I'm looking to get `typehole` traffic out of container using some native solutions, for now ended up here:

https://github.com/docker/compose/issues/3532

Same issue, to use `overlay` network and `host` network at the same time. If I were to find a solution, I'll update here for posterity.
