### ISSUE TITLE
typehole not working with angular?

### ISSUE THREAD

**Issue by bertutron** [rikukissa/typehole#15]
I installed the vscode extension, but in quickfix menu, the 'add typehole' entry is missing. I'm trying this in an angular application, is this supposed to work with angular?

**Comment by rikukissa** [comment]
Typehole is supposed to work in any TS files as long as the files can be parsed by the TS compiler. 
Code actions are available for `typescript` and `typescriptreact` language identifiers https://code.visualstudio.com/docs/languages/identifiers . This seems like a bug to me. What would be a good example Angular project for me to try and debug this?

**Comment by bertutron** [comment]
ok, it seems to work now. i cannot reproduce it. got some failures that i have to manually install typehole, after 'ng add typehole' it worked. insanely helpful tool.

thanks for responding so fast anyway ^^

**Comment by rikukissa** [comment]
No worries at all, and I'm glad you find it helpful :) Let me know if other issues come up!
