### ISSUE TITLE
Why is export 'default output xxx'? I'm expecting an interface

### ISSUE THREAD

**Issue by lmxyjy** [rikukissa/typehole#17]
hi，dear author:
I try use 'typehole' in my react project.but I don't get an interface。Export Default XXX is printed every time I compile, which causes my program to execute incorrectly.

my code is :
![image](https://user-images.githubusercontent.com/48620706/119314724-a5135500-bca7-11eb-8c48-44351931650a.png)

**Comment by rikukissa** [comment]
Hey! This is interesting. Typehole should not add any export statements to the file, which makes me think it might be some other extension doing this. Which formatter are you using? Typehole does invoke the default formatter for the file, but that happens only after the type/interface has been inserted. Looking at your screenshot, it seems no type has been inserted yet.
I'll see if I can reproduce this in my own environment. 

>Export Default XXX is printed every time I compile

Could you also elaborate on this? Does it happen right after you add the typehole and hit save or only after your browser runs the code?

**Comment by rikukissa** [comment]
Could you also check if you can reproduce the issue by using the "Format the document..." commands?

![image](https://user-images.githubusercontent.com/1206987/119357751-98472f00-bcb0-11eb-89a0-4350d58ecf07.png)

**Comment by lmxyjy** [comment]
thanks your answer, I discovered the cause of the problem. As you said, it's really formatting. This problem was resolved when I shut down Prettier.

![image](https://user-images.githubusercontent.com/48620706/119425732-7a261100-bd3a-11eb-872a-022a7554a620.png)

I have a feeling that VS Code plugins can easily conflict with each other. Your typehole makes me feel very useful. Especially if I want the type of data that needs to be retrieved from the interface.

While it's easy for me to use on my own, to use it on a team, everyone needs to have this extension installed. So have you considered making it a project configuration like ESLint?

**Comment by rikukissa** [comment]
Excellent. Yeah, you might be right. Typehole is calling the default formatter, which in turn can do pretty much anything.

If many people in your team want to use it, I'd suggest you create a `.vscode/extensions.json` file to the root of your project.
All Typehole settings can also be stored under the `.vscode` directory, just like you'd share other VSCode settings.

```typescript
{  
  "recommendations": [ 
     "rikurouvila.typehole"
   ]
}
```
