### ISSUE TITLE
Allow choosing `type` instead of `interface`

### ISSUE THREAD

**Issue by akafaneh** [rikukissa/typehole#19]
I use `type` in my project almost for everything, and i just want to keep it consistent, so if we can have a property to choose between them if possible.
Great tool btw, thanks

**Comment by rikukissa** [comment]
That's definitely something that I'd want to see configurable as well. The type generation is done by json-to-ts library that I've forked [here](https://github.com/rikukissa/json-to-ts). My first guess is that the change would have to be done there. I'll have a look as soon as I have time, but if you wish to contribute, I'm very much open to PRs :)

**Comment by akafaneh** [comment]
@rikukissa Check the [PR](https://github.com/rikukissa/json-to-ts/pull/1) please and let me know what you think

**Comment by rikukissa** [comment]
Added in [1.7.0](https://github.com/rikukissa/typehole/releases/tag/1.7.0) 👍
