### ISSUE TITLE
typehole.tNaN

### ISSUE THREAD

**Issue by rikukissa** [rikukissa/typehole#7]
It seems if you add a new typehole that doesn't have the "typehole.t[number] format, the next typehole you'll add with cmd+. will cause the name if the whole to be tNaN.

I think a possible solution for this would be to just treat the method labels as strings

**Comment by andrew-ironforge** [comment]
Looking at this a bit more... (From Reddit!).

I am still running into the issue. Attached is a screen recording.

https://user-images.githubusercontent.com/29921020/118546620-d0cd9280-b71d-11eb-8498-4c466f1663dc.mov

I have no other type holes in the project:
<img width="382" alt="Screen Shot 2021-05-17 at 2 40 46 PM" src="https://user-images.githubusercontent.com/29921020/118546662-e0e57200-b71d-11eb-83aa-d6e86b43f6c5.png">

**Comment by andrew-ironforge** [comment]
If I reload the window, the issue does not occur. So it seems to me that perhaps there's some kind of caching issue that is resolved when the editor is reloaded? Clearing out all type holes from the project doesn't fix it... a reload is required.

**Comment by rikukissa** [comment]
👋 It must have been Typehole's internal state and the overly naive implementation for figuring out an id for the next hole based on the previous ids. If one of the previous ids were not possible to parse to an integer, then `previous + 1` would be NaN. I'll make it so that all typehole ids are treated as strings and come up with another way for figuring out new unique ids. 

Thanks for the video and a good issue description. Much appreciated

**Comment by rikukissa** [comment]
Should now be fixed in [1.5.1](https://github.com/rikukissa/typehole/releases/tag/1.5.1).
